theme: jekyll-theme-minimal
title: Mantaro
description: A simple, useful and comprehensive Discord bot.
logo: https://i.imgur.com/MjhqupN.png
patreon_url: https://patreon.com/mantaro
support_url: https://support.mantaro.site
wiki_url: https://www.mantaro.site/mantaro-wiki
twitter_url: https://twitter.com/mantarodiscord
invite_url: https://discord.com/oauth2/authorize?client_id=213466096718708737&scope=applications.commands%20bot&permissions=3525702
