theme: jekyll-theme-minimal
title: Mantaro
description: A simple, useful and comprehensive Discord bot.
logo: https://i.imgur.com/4ngQfpY.jpg
patreon_url: https://patreon.com/mantaro
support_url: https://support.mantaro.site
wiki_url: https://wiki.mantaro.site
twitter_url: https://twitter.com/mantarodiscord
